### ISSUE TITLE
Create json printer

### ISSUE THREAD

**Issue by rikatz** [rikatz/kubepug#11]
Create an optional json printer instead of using the tree printing

**Comment by chentex** [comment]
I would like to tackle this one.

**Comment by rikatz** [comment]
@chentex It would be great :)

I was going to take a time to refactor some stuff and make this easy (as instead printing directly putting this into a struct and then creating a Printer Method to allow user to print as json, csv and so on), but go ahead and implement by your ways :)

I'll wait anxiously it :)

Thank you!

**Comment by chentex** [comment]
So @rikatz , I have been playing a bit with the code and getting some ideas on how to do it correctly, this is my take.

![Kubepug](https://user-images.githubusercontent.com/757508/75559216-5bf03900-5a43-11ea-96b7-9d6c7cfb36f2.png)

(This is your project, so you are entitled to disagree or correct it :+1: )

**Comment by rikatz** [comment]
@chentex tks for following with this. I think the idea is fine :) I’m traveling a lot in the past (and this) weeks and that’s why I’m taking a bit longer to answer, but I’ll take a better look asap (probably this week)! 

But you can start following by this proposal, seems nice to me :)

**Comment by rikatz** [comment]
@chentex got some time now to read. The idea is great, it's simple and yet will work nicely.

I think it also will allow in a future to implement some other features, as the selection of the indexer (imagine you want to index deprecated objects by namespace instead of apiGroup).

Let me know if you need something else to start working on this, otherwise you can go forward.

Thank you!

**Comment by chentex** [comment]
I submitted a PR with most of the changes, I am checking an error that I have when I run with the `api-walk` option, as soon as I know why this is happening I will update with the last part.

Since it is a lot of changes it makes sense to me to open a PR to start reviewing.

Let me know if you want to change anything.

(I still have some debug messages in there.)

**Comment by rikatz** [comment]
Great! I’ll probably take some time in the weekend to start reviewing and testing :)
