### ISSUE TITLE
Kind List not supported

### ISSUE THREAD

**Issue by knelasevero** [rikatz/kubepug#111]
Templates of kind list always comes back with an "deleted api" report.

Will happen if you run kubepug against yamls files like in the exemple for ResourseQuotas https://kubernetes.io/docs/concepts/policy/resource-quotas/

**Comment by rikatz** [comment]
Thank you for the report! Can confirm.

This is due I try to parse the yaml, instead of using things already done by client-go or kubectl.

I'll have to dig deeper into how kubectl parses this and maybe use kubectl function instead of trying to parse everything all by myself :D
