### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by RudyBone** [rikatz/kubepug#118]
We are looking at upgrading our Cluster from v1.14.9 to v1.18.0.  It's not clear to me whether I should pull the v1.14 swagger json or the v1.18 json.

**Comment by rikatz** [comment]
Hello and thanks for your interest in the project.

You should use the v1.18 version (--k8s-version=v1.18.9), because you're going to validate the objects from your cluster against their existence in the v1.18.9 version.

Let me know if this answers your question :)

**Comment by RudyBone** [comment]
That's what I thought, just wanted to make sure.

Thanks
