### ISSUE TITLE
Add link to the release page in the documentation

### ISSUE THREAD

**Issue by gilgougnot** [rikatz/kubepug#183]
In the readme file, on [How to use it as standalone program](https://github.com/rikatz/kubepug/blob/main/README.md#how-to-use-it-as-a-standalone-program), it says 

> Download the correct version from Releases page.

There is no mention of where this release page is, so the user does not know from where it needs to download the software.

Acceptance criteria: 
the user see a link to the URL pointing to the release page on the words "Releases page"
When clicking on the link, the user's browser open a new tab and the release page is displayed.

Would really appreciate, Thx !

**Comment by rikatz** [comment]
hey, thanks for the suggestion :)

do you mind opening a PR for README? Otherwise I can do that, but probably later this week

Thanks!

**Comment by gilgougnot** [comment]
hi there sorry but i can not.
I wanted to test your tool (back in july) but could not install it as I did not find this release page.
This is really stupid blocker I would say, that s why I opened this issue.

**Comment by rikatz** [comment]
Fixed in https://github.com/rikatz/kubepug/commit/42529d7c573cbc2f5cb8d4810b715b29b76e0289
