### ISSUE TITLE
Binary assets missing for 1.2.0+

### ISSUE THREAD

**Issue by jackwhelpton** [rikatz/kubepug#197]
The instructions for using KubePug as part of a CI pipeline suggests downloading:

https://github.com/rikatz/kubepug/releases/latest/download/kubepug_linux_amd64.tar.gz

This redirects to:

https://github.com/rikatz/kubepug/releases/download/v1.2.1/kubepug_linux_amd64.tar.gz

which gives a 404. I suspect this is because the binaries have not been generated for 1.2.0 or 1.2.1. The following works:

https://github.com/rikatz/kubepug/releases/download/v1.1.3/kubepug_linux_amd64.tar.gz

**Comment by rikatz** [comment]
gonna work on this right now :D

**Comment by rikatz** [comment]
Hey,

I have released v1.2.2, now supporting the Apple M1 :) and the assets are there.

Can you please check and let me know?

Thanks!

**Comment by jackwhelpton** [comment]
lgtm, thanks!

**Comment by eyenx** [comment]
Thanks @rikatz
