### ISSUE TITLE
Invalid VerticalPodAutoscaler deprecation

### ISSUE THREAD

**Issue by agutoli** [rikatz/kubepug#215]
Hello, currently I use this plugin to validate local k8s manifest files which works pretty well. I realised last updates probably introduced an issue with k8s `v1.18.0` + `autoscaling.k8s.io/v1beta2` VPA. 

It says that k8s `v1.18.0` removed `autoscaling.k8s.io/v1beta2`, but actually it supposed to be delete next k8s versions.

kubectl-deprecations --k8s-version v1.18.0 --input-file datadog-v7/agent-vpa.yaml --error-on-deleted

RESULTS:
Deprecated APIs:

Deleted APIs:

VerticalPodAutoscaler found in autoscaling.k8s.io/v1beta2
	 ├─ API REMOVED FROM THE CURRENT VERSION AND SHOULD BE MIGRATED IMMEDIATELY!!
		-> OBJECT: datadog-agent namespace: kube-system location: datadog-v7/agent-vpa.yaml

Error: found 1 Deleted APIs and 0 Deprecated APIs
time="2021-11-30T01:08:16Z" level=error msg="An error has occurred: found 1 Deleted APIs and 0 Deprecated APIs"

**Comment by rikatz** [comment]
Hello thanks for the issue. Will take a look later this week to see if this is a well known problrm :/

thanks!

**Comment by rikatz** [comment]
VerticalPodAutoscaler is one of those cases where an API has a group (like autoscaling.k8s.io) but it is not an official API, so it should be at x-k8s.io :) 

I will add it to the ignored list for the next releases

**Comment by rikatz** [comment]
fixed in https://github.com/rikatz/kubepug/pull/403/commits/08f56593649e8409a3a30c0fd11a8429eb631b19 

VerticalPodAutoscaler is a CRD using a group it shouldn't (k8s.io is reserved for Core APIs) :) 
We don't have a way, today to verify CRDs deprecations.

Will be available on the next alpha release, thanks for using the project!
