### ISSUE TITLE
How this compare to kube-no-trouble?

### ISSUE THREAD

**Issue by daxmc99** [rikatz/kubepug#241]
This is more a question than an issue. 

This project seems to have some overlap with [kube-no-trouble](https://github.com/doitintl/kube-no-trouble) 

The difference that I see from the outside is that this is a `krew` plugin while the other is no. 
Is that the only major difference?

**Comment by rikatz** [comment]
kubent apparently uses rego rules: https://github.com/doitintl/kube-no-trouble/blob/master/pkg/rules/rego/deprecated-1-25.rego

kubepug uses the swagger.json from the Kubernetes API so you can see what changed and was removed between versions, pointing to a specific version.
