### ISSUE TITLE
ux: hide red section(s) if no results found

### ISSUE THREAD

**Issue by Dentrax** [rikatz/kubepug#249]
For example, if no `Deleted APIs` or `Deprecated APIs` found, had better to not print out these sections to better UX.

![Screen Shot 2022-05-11 at 14 46 19](https://user-images.githubusercontent.com/16493751/167842252-877d3896-87f6-4d5b-9999-524ca47664fb.png)

```
$ kubectl deprecations version

GitVersion:    devel
GitCommit:     a87116d84a3531dca9975db25adedc91d8a3fb8d
GitTreeState:  clean
BuildDate:     '2021-11-29T14:26:19Z'
GoVersion:     go1.17.3
Compiler:      gc
Platform:      darwin/amd64
```

**Comment by rikatz** [comment]
Fixed in #419 
I'm cutting a new beta release soon
