### ISSUE TITLE
No release of plugin for linux/arm64

### ISSUE THREAD

**Issue by lunderhage** [rikatz/kubepug#287]
There is no installation candiate for linux/arm64:

```
$ kubectl krew install deprecations
Updated the local copy of plugin index.
Installing plugin: deprecations
W0908 11:16:30.804269  283560 install.go:164] failed to install plugin "deprecations": plugin "deprecations" does not offer installation for this platform
failed to install some plugins: [deprecations]: plugin "deprecations" does not offer installation for this platform
```

There is a growing number of users on non-intel platforms such as Apple Silicon, Raspberry Pi etc.

Please make a release of this excellent plugin for linux on arm64!

**Comment by rikatz** [comment]
@lunderhage thanks and sorry for the 1 year delay :(

We did a release (https://github.com/rikatz/kubepug/releases/download/v1.4.0/kubepug_linux_arm64.tar.gz), can you check if this works?

It is already configured for the next releases as well.

Thanks

**Comment by rikatz** [comment]
I'm assuming this release works, but please feel free to re-open the issue or reach me in Kubernetes Slack.

Thanks!!
