### ISSUE TITLE
Support Snap package

### ISSUE THREAD

**Issue by patsevanton** [rikatz/kubepug#293]
Hello! Thanks for [kubepug](https://github.com/rikatz/kubepug)
Could project create snap package?

**Comment by rikatz** [comment]
Hey @patsevanton thanks for using the project.

I need to take a look on how to do it. (and also on brew probably!) Do you have any clues? :D Thanks!

**Comment by rikatz** [comment]
@patsevanton started to implement this, I have already reserved the snap name `kubepug` and was able to build it successfully.

I just need to get my snap login working somewhere here, as my remote build machine is not able to get logged in correctly, then after publishing the first package the other ones should be automatic

**Comment by rikatz** [comment]
Snap is available now at https://snapcraft.io/kubepug and being built linked to the repo, thanks for using the project!
