### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget resources not reported

### ISSUE THREAD

**Issue by alshain** [rikatz/kubepug#378]
We used kubepug to scan our cluster before upgrading from K8S v1.24.6 to v1.25.6.

It didn't catch our `policy/v1beta1`/`PodDisruptionBudget` usages. Apparently because K8S already migrated these objects internally? (Is this behavior documented somehwere?)

#92 and the fix #96 seems to be about the same issue, but it apparently didn't take for our case.

I re-verified using kubectl apply on a v1.24.6 cluster, a v1beta1 PDB is then returned as v1, but maybe it also just looks that way because the client uses the v1 API to fetch them? 

```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: 
  annotations:
    kubectl.kubernetes.io/last-applied-configuration:                                                          
       {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"irrelevant-rabbitmq-temp","namespace":"irrelevant"},"spec":{"minAvailable":1,"selector":{"matchLabels":{"app.kub │
│ ernetes.io/instance":"irrelevant","app.kubernetes.io/name":"rabbitmq"}}}}
...
```

Of course, when using Helm, the annotation showing `v1beta1` wouldn't be there.

```
GitVersion:    v1.4.0
GitCommit:     4de32d695b27c52c16d4a801b613b78e45e28ca9
GitTreeState:  clean
BuildDate:     2022-08-21T18:25:40
GoVersion:     go1.18.5
```

**Comment by rikatz** [comment]
Hi @alshain, that's right.

What happens is that Kubernetes defines a preferred API version per release, and from v1.24.6 to v1.25.6 the preferred version for PDB may have changed from v1beta1 to v1. 

I need to double check if this means that the etcd storage also got updated when you migrated, or if it still points to the old v1beta1 but re-touches to v1. 

We don't have a way to define how the object is persisted on the database, to see if it was migrated during the upgrade or not. Anyway, I'm double checking here if I can get some field/indicative of how the object was persisted

**Comment by rikatz** [comment]
@alshain I have confirmed with some folks here once you migrate your k8s version, the APIs are also updated. The idea of raising an alert on deprecation in Kubepug is if you are planning to do a jump migration (from v1.19 to v1.24 for instance) you may not have the API converted :)

I'm closing this, but feel free to re-open or reach me on Kubernetes Slack, thanks for using the project!
