### ISSUE TITLE
Rename binary to kubectl-pug

### ISSUE THREAD

**Issue by mrueg** [rikatz/kubepug#38]
Thanks for writing this plugin!

It would be awesome if the binary can be renamed kubectl-pug in future releases, as per:

https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#installing-kubectl-plugins
`A plugin is nothing more than a standalone executable file, whose name begins with kubectl-. To install a plugin, simply move its executable file to anywhere on your PATH.`

**Comment by rikatz** [comment]
Hi @mrueg and thanks for raising this.

There was some discussion about this here: https://github.com/kubernetes-sigs/krew-index/pull/438#issuecomment-574893786

And this is why the plugin is called ``deprecations`` and not pug. However if you think this should be different, let me know, we can discuss further :)

And thank you for using the plugin, I hope this keeps being useful :)

**Comment by mrueg** [comment]
Yep understood, got it now. Thanks!
