### ISSUE TITLE
externaldns.k8s.io/v1alpha1 DNSEndpoint reported as deleted

### ISSUE THREAD

**Issue by arturhoo** [rikatz/kubepug#386]
From a quick glance at the code https://github.com/rikatz/kubepug/blob/f943596843167b2ca4e51f73ffa7e269cab77352/pkg/kubepug/input/file/deleted.go#L22-L24 it seems that we want to skip CRDs, unless they contain `k8s.io` in them.

However, this leads to CRDs like `DNSEndpoint` from `externaldns.k8s.io/v1alpha1` to be reported as deleted:

```
DNSEndpoint found in externaldns.k8s.io/v1alpha1
	 ├─ API REMOVED FROM THE CURRENT VERSION AND SHOULD BE MIGRATED IMMEDIATELY!!
```

This happens if a `swagger.json` from the cluster is downloaded locally and checked against a file. However, it is not reported when running against a live cluster. Just wanted to know if this is an expected behaviour. If not, happy to contribute with a patch.

**Comment by rikatz** [comment]
ah yeah, because this API should be at x-k8s.io and not at k8s.io.

I plan on adding some proper "ignore" config, and also see if we can validate those API groups based on some additional repos

**Comment by rikatz** [comment]
@arturhoo can you test with https://github.com/rikatz/kubepug/releases/tag/v1.5.0-alpha.0 and let me know please?

**Comment by rikatz** [comment]
fixed on https://github.com/rikatz/kubepug/pull/402/files#diff-553451f075eb3dfbab97c88354dc8e391e04c2d96f6603b2a848534e60bdc319R99 

Please let me know / reopen if this still happens! Thanks for using the project :)
