### ISSUE TITLE
Support offline swagger files

### ISSUE THREAD

**Issue by mrueg** [rikatz/kubepug#39]
In some environments, internet is inaccessible. It would be great if kubepug had a command line option to support a local file as input.

**Comment by rikatz** [comment]
Hi @mrueg and thanks for raising the issue. I’m OOO this week but will take a look next week :)

**Comment by rikatz** [comment]
Hi @mrueg 

Kubepug already supports offline execution, thus it's not well documented.

You can download the swagger.json file from ``https://raw.githubusercontent.com/kubernetes/kubernetes/v1.17.0/api/openapi-spec/swagger.json`` (or whatever version you want) to some directory, and point kubepug to use this directory with the flag ``--swagger-dir``.

As an example, imagine you've downloaded the swagger.json to ``/opt/kubepug/swagger.json``:

* Rename it to reflect the version you wan't to use, turning it into ``/opt/kubepug/swagger-v1.17.0.json``

* Run kubepug with the following: ``./kubepug --k8s-version=v1.17.0 --swagger-dir=/opt/kubepug`` and voilá, it should work.

I'll keep this issue open to at least document this, but let me know if this solves your problem :)

**Comment by mrueg** [comment]
Thanks for your response @rikatz and thanks for the documentation @chentex
