### ISSUE TITLE
Aggregated apiserver APIs are marked as removed

### ISSUE THREAD

**Issue by morremeyer** [rikatz/kubepug#413]
#40 seems to be happening again with the 1.5.0 rewrite - I just upgraded and it shows the metrics-server APIs as removed for v1.27.0.
I verified against 1.4.0 where this is not happening.

**Comment by Vad1mo** [comment]
can confirm, see the same issue, needed to revert back to 1.4

**Comment by rikatz** [comment]
Hum sorry for that folks. Will check tomorrow my morning and release a bugfix :)

**Comment by rikatz** [comment]
yeap, my bad, re-added the ignore for aggregated APis here, should be fixed on the next release!

Thanks for reporting it
