### ISSUE TITLE
Is there a way to check upstream helm chart?

### ISSUE THREAD

**Issue by rd-michel** [rikatz/kubepug#434]
Is it already possible to check an non-local helm chart (without downloading the chart manually)?

otherwise ... would be nice to put this on the kubepug 2.0 wishlist. what do you think?

**Comment by rikatz** [comment]
Hi there, this sounds like a great idea :) 

Usually what I've heard is people doing a "helm template" and passing it to stdin, doesn't this works? I will take some time next week to look into it, otherwise :)
