### ISSUE TITLE
can't have a plugin without specifying file operations

### ISSUE THREAD

**Issue by estahn** [rikatz/kubepug#64]
```
kubectl krew install deprecations
Updated the local copy of plugin index.
F0429 16:49:52.796455   13476 root.go:52] failed to load plugin "deprecations" from the index: platform ({Head: URI:https://github.com/rikatz/kubepug/releases/download/v0.2.6/kubepug_darwin_amd64.tar.gz Sha256:d583c80786e1c0c67aa65b8824680ae5f3f229cf80c5d9c52a5efc0a20a494e0 Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:kubepug}) is badly constructed: can't have a plugin without specifying file operations
```

**Comment by rikatz** [comment]
Hi @estahn thanks for raising this.

I'll take a look this friday to check what's happening and will return ASAP.

Thank you

**Comment by rikatz** [comment]
@estahn I don't have a Mac to test here :( 

But I've just made a fresh install of krew and kubepug into Linux and it worked fine. I now this error is returning from krew and not Pug, but I've double checked the releases files and also the plugin configuration in index and it seems right.

Just to know, what's the version of krew you're using? ``kubectl krew info krew``

I'll try to get someone with a MacOS here to test for me also the installation so we can isolate what's going on.

Thank you!

**Comment by mcristina422** [comment]
I was able to install kubepug v0.2.6 on a Mac using krew v0.3.2

**Comment by estahn** [comment]
Thanks for checking this out. I had an old version of krew. It worked after upgrading krew.

**Comment by rikatz** [comment]
Thank you @mcristina422 and @estahn for using Kubepug :) hope this is useful for you, feel free to open issues whenever needed

**Comment by estahn** [comment]
> Thank you @mcristina422 and @estahn for using Kubepug :) hope this is useful for you, feel free to open issues whenever needed

It is exactly the tool I was looking for. There are couple others based on OPA policy language, but that requires to build-out the rules by yourself. I like your approach with swagger. 👍
