### ISSUE TITLE
exit 1 if upgrade would be a breaking change

### ISSUE THREAD

**Issue by grosser** [rikatz/kubepug#67]
let's say I upgrade to 1.18 ... then I don't need to fix v1.19 deprecations

```
	 ├─ MutatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and may change the object. 
Deprecated in v1.16, planned for removal in v1.19. Use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration instead.
```

so it would be nice if I can get a `exit 1` for "this will break in 1.18" so I can automate this task nicely against all clusters

**Comment by rikatz** [comment]
@grosser hello and thanks for the issue :D

I was planning to put this flag while dealing also with issue #65 so it makes a lot of sense also the CI breaking :)

I'll put this into the next release and probably work into those features this week :)

**Comment by grosser** [comment]
:D

**Comment by rikatz** [comment]
Now present in v1.0.1

**Comment by grosser** [comment]
thx!
