### ISSUE TITLE
Output kubepug's version

### ISSUE THREAD

**Issue by mstoetzer** [rikatz/kubepug#71]
Is there a way to output kubepug's own version? To see if I need to upgrade the Pre UpGrade (Checker) ;-)

**Comment by rikatz** [comment]
Oh this is embarrassing :/ I'll ship it ASAP, as this is pretty simple to correct :)

Thank you!

**Comment by mstoetzer** [comment]
You're great! Thank you :)

**Comment by gcbw** [comment]
Downloaded the latest release as of now https://github.com/rikatz/kubepug/releases/tag/v1.3.3

```
$ kubepug --version
Error: unknown flag: --version
ERRO[0000] An error has occurred: unknown flag: --version

$ kubepug version
GitVersion:    devel
GitCommit:     ab7f00bbfb1c84ffa23ad37630d3caeaad1ed221
GitTreeState:  clean
BuildDate:     '2022-04-04T11:27:28Z'
GoVersion:     go1.17.8
Compiler:      gc
Platform:      linux/amd64

```
