### ISSUE TITLE
Deprecated resource being shown in multiple API groups

### ISSUE THREAD

**Issue by codescalar** [rikatz/kubepug#72]
Thank you for your work on this project, seems very useful!

I installed kubepug just now and I'm seeing resources being flagged as deprecated in multiple API groups which creates a lot of noise. An example of what I mean:

On my v1.15 cluster, `kubectl deprecations --k8s-version=v1.16.0` returns:

```
RESULTS:
Deprecated APIs:

Deployment found in apps/v1beta1
	 ├─ DEPRECATED - This group version of Deployment is deprecated by apps/v1beta2/Deployment. See the release notes for more information. Deployment enables declarative updates for Pods and ReplicaSets.
		-> OBJECT: cert-manager namespace: cert-manager
		-> OBJECT: cert-manager-cainjector namespace: cert-manager
		-> OBJECT: cert-manager-webhook namespace: cert-manager

[...snip...]

Deployment found in apps/v1beta2
	 ├─ DEPRECATED - This group version of Deployment is deprecated by apps/v1/Deployment. See the release notes for more information. Deployment enables declarative updates for Pods and ReplicaSets.
		-> OBJECT: cert-manager namespace: cert-manager
		-> OBJECT: cert-manager-cainjector namespace: cert-manager
		-> OBJECT: cert-manager-webhook namespace: cert-manager

[...snip...]

Deployment found in extensions/v1beta1
	 ├─ DEPRECATED - This group version of Deployment is deprecated by apps/v1beta2/Deployment. See the release notes for more information. Deployment enables declarative updates for Pods and ReplicaSets.
		-> OBJECT: cert-manager namespace: cert-manager
		-> OBJECT: cert-manager-cainjector namespace: cert-manager
		-> OBJECT: cert-manager-webhook namespace: cert-manager

```

This is happening for all resource groups (i.e Replicasets, Ingress, etc), not just Deployments.

I'm guessing this is related to the fact that the k8s API server will automatically marshall between apiversions as can be seen when specifying the apiversion with `kubectl get` as seen below. Note that these are the same resource, just a different representation.

`kubectl -n cert-manager get deployment.v1beta1.extensions -o yaml`
```
[...snip...]
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: cert-manager
    namespace: cert-manager
[...snip...]
```
versus:
`kubectl -n cert-manager get deployment.apps -o yaml`
```
[...snip...]
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cert-manager
    namespace: cert-manager
[...snip...]
```

**Comment by codescalar** [comment]
I should also mention that some of the deprecated resources being returned were in fact created using the latest api version (e.g. apps/v1 for Deployments) but are still shown as deprecated (e.g. extensions/v1beta1 for Deployments) by kubepug. 

Seems like the same issue related to how kubepug is requesting the resource and how the k8s api server marshalls between api versions depending on the client's request.

**Comment by rikatz** [comment]
@codescalar tks for raising this issue!

I'll take a look during this week and the next. The program makes a map of all existing objects in the current swagger and checks which have the 'deprecated' text in their description, trying to get them and so yes, this might happen. Didn't realize that the API could return all of them even if the stable object also exists :)

I'll figure out a way to correlate them and if the object exists both in the stable and the deprecated API remove it from the output :)

Thank you!

**Comment by codescalar** [comment]
No problem and no rush, just wanted to let you know! I didn't realize the
API server had this behavior either until just today :)

**Comment by rikatz** [comment]
Hey @codescalar :wave: 

Just passing here to let you know that I didn't forgot about this. I was refactoring the whole thing here to allow input files and then dealing with this also became easier :)

I'll probably solve this next weekend.

Thank you

**Comment by codescalar** [comment]
Thanks @rikatz!

**Comment by rikatz** [comment]
Well, the guessing here is pretty "hard" as I need to cross between each deprecated object and if it exists in some different API :/

I'm thinking about using the discovery library to feed the API with another struct containing all the preferred names and when something from swagger.json is found, check if there's that same resource name as an stable version.

The final movement is to check if the list length of objects containing the deprecated objects is the same length of the list of objects with the maybe preferred name and assume everything is fine :)

Let me see if this works, will need some testing here because IMO it's worst having a false negative than a false positive in this case :)
