### ISSUE TITLE
False positive detected deprecation ?

### ISSUE THREAD

**Issue by yogeek** [rikatz/kubepug#79]
Hi and thanks for this useful krew plugin :)

I just installed it and when I test it on my 1.16.6 cluster, I am not sure to understand the output.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl krew list                
PLUGIN             VERSION
deprecations       v1.0.1
```

The plugin indicates multiple deprecated version, here is an extract of the output :
```
$ kubectl deprecations --kubeconfig=~/.kube/config

RESULTS:
Deprecated APIs:

RoleBinding found in rbac.authorization.k8s.io/v1beta1
	 ├─ RoleBinding references a role, but does not contain it.  It can reference a Role in the same namespace or a ClusterRole in the global namespace. It adds who information via Subjects and namespace information by which namespace it exists in.  RoleBindings in a given namespace only have effect in that namespace. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 RoleBinding, and will no longer be served in v1.22.
		-> OBJECT: cert-manager-webhook:dynamic-serving namespace: cert-manager

[...]

ClusterRoleBinding found in rbac.authorization.k8s.io/v1beta1
	 ├─ ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject. Deprecated in v1.17 in favor of rbac.authorization.k8s.io/v1 ClusterRoleBinding, and will no longer be served in v1.22.
		-> GLOBAL: calico-kube-controllers 
		-> GLOBAL: calico-node 
[...]
```

But when I display the apiVersion of some of the detected objects, it seems to already be in the right API version :
```
$ kubectl get rolebindings.rbac.authorization.k8s.io -n cert-manager cert-manager-webhook:dynamic-serving -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
[...]


$ kubectl get clusterrolebindings.rbac.authorization.k8s.io calico-kube-controllers -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
[...]

$ kubectl get clusterrolebindings.rbac.authorization.k8s.io calico-node -o yaml            
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
```

Did I misunderstand something ?
Thank you

**Comment by rikatz** [comment]
Hi @yogeek and thanks for the issue :)

You're right, this is a false positive. This has been already mapped in #72 and it's in my backlog.

I'm finishing to re-structure the code so it will be easier to put each behavior in each input format, as this is a false positive when you're using a k8s cluster but not when you're using an input file :)

I'll keep this open just to make sure those are the same issues and I'm not letting anything pass, and expect to correct this by the weekend :)

Thank you!

**Comment by rikatz** [comment]
@yogeek I'm closing this in favor of #72 but please feel free to reach me or reopen if you think those are different issues :)

Thank you

**Comment by yogeek** [comment]
Hi @rikatz ! Just a quick question : after I opened this issue, I noticed that the resource apiVersion was indeed rbac.authorization.k8s.io/v1 but the "last-applied" configuration apiVersion was in beta... Does it mean the YAML that were applied to the cluster contained 'beta' but during the apply, kubernetes modified it to set the 'v1' apiVersion ? Is it possible ?
And do your tool look at the real apiVersion or at the 'last-applied' one ?

**Comment by rikatz** [comment]
Hey @yogeek 

About the last-applied, it's an annotation containing the marshalled JSON used to apply to kube-apiserver but AFAIK annotations are just metadata put by the object owner (like the user, the developer) or by the controller to represent something. It shall not be used to control the behavior of the object in the cluster, EXCEPT in cases like Ingress Controllers that still uses annotations in Ingress Objects as this was the best way to achieve this.

And this is why also CRD came to life and are turning the de-facto objects for non existing things in the Core of Kubernetes :)

So no, this annotation should not represent how the object is persisted in apiserver (and ETCD). Probably the api server mutates the object before persisting it in the etcd server, and I should think that also when you migrate from a version to other the apiserver might convert those objects if this is supported but I really need to test.

I've made a quick test here, creating a ClusterRoleBinding with the stable/final version (rbac.authorization.k8s.io/v1) and then getting the v1beta1 and it was returned in both listings, so my guess is that the API Server have a preferred GroupVersion (that I'm using in the code that will convert this here) but it still accepts if you want to get the older beta version.

About the tool, the approach is slight different: It lists all the possible APIs that Kubernetes might have using the swagger.json and with the description containing the "DEPRECATED" word and then tries to fetch each of them in the cluster. If the list is bigger then 1 (that happens as we have seen in this bug) it marks all the objects as deprecated.

The change of approach here is going to be: Gets all the APIs and their Preferred GroupVersion (like ClusterRoleBinding have rbac.authorization.k8s.io in v1 and v1beta1), checks if there's an object in the deprecated api group/version, if so checks the preferred group/version for that same resource and if the length is the same (meaning those are the same API Resources but in different groups), pass to the next as this might not be deprecated :)
