### ISSUE TITLE
Feature: GitHub Action

### ISSUE THREAD

**Issue by estahn** [rikatz/kubepug#83]
A GitHub action to simplify usage in CI would be great.

Just did a quick test with the following:
```
  api-deprecations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: kubepug
        run: |
          mkdir -p ~/bin
          curl -sSL https://github.com/rikatz/kubepug/releases/download/v1.1.0/kubepug_linux_amd64.tar.gz | tar xvfz - --overwrite -C ~/bin/
          curl -sSL https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz | tar xvfz - -C ~/bin/ --wildcards --strip 1 '*/helm'
          
          find charts -mindepth 1 -maxdepth 1 -type d | xargs -t -n1 -I% /bin/bash -c '~/bin/helm template % | ~/bin/kubepug --error-on-deprecated --error-on-deleted --k8s-version v1.16.0 --input-file /dev/stdin'
```

I probably should provide the kubernetes version to helm as well.

**Comment by rikatz** [comment]
Got it, it's on backlog now :D

I'll prioritize now putting some unit tests first, as I've missed them a lot when refactoring things and then move into this :)

If you want to catch this one and maybe open a PR, go ahead :D

**Comment by rikatz** [comment]
@estahn PTAL at https://github.com/rikatz/kubepug/pull/100 and check if this is the idea. It's really nice to see kubepug moving on, thank you for the contribution.

Also I've made some tests in https://github.com/rikatz/pug-tests/runs/1018853600?check_suite_focus=true and it seems to work as desired
